site_name: Learing QEMU Docs
site_author: GTOC
repo_name: gevico/learning-qemu-docs
repo_url: https://github.com/gevico/learning-qemu-docs
copyright: Brought to you by <a href="https://github.com/gevico/">Gevico Tech Open Community</a>. Available freely under the Apache-2.0 license.

theme:
    name: material
    palette:
        scheme: auto

extra_css:
    - theme/css/import.css

extra_javascript:
    - theme/js/zoom.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 训练营介绍: index.md
  - 1. 导学阶段: ch0/index.md
  - 2. 基础阶段: ch1/index.md
  - 3. 专业阶段: ch2/index.md
  - 4. 项目阶段: ch3/index.md 

