site_name: Learning QEMU Docs
site_author: GTOC
repo_name: gevico/learning-qemu-docs
repo_url: https://github.com/gevico/learning-qemu-docs
copyright: Brought to you by <a href="https://github.com/gevico/">Gevico Tech Open Community</a>. Available freely under the Apache-2.0 license.

theme:
    name: material
    logo: image/Qemu-logo.png
    palette:
        scheme: auto

extra_css:
    - theme/css/import.css

extra_javascript:
    - theme/js/zoom.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
    - mkdocs-audio

nav:
  - 训练营介绍: index.md
  - 1. 导学阶段: ch0/index.md
  - 2. 基础阶段:
    - a. 本章导览: ch1/index.md
    - b. 虚拟机发展历史: ch1/sec1/vm-history.md
    - c. Hypervisor 技术介绍: ch1/sec2/hypervisor.md
    - d. QEMU 基本知识介绍:
      - QOM: ch1/sec3/qemu-qom.md
      - MemoryRegion: ch1/sec3/qemu-memory-region.md
  - 3. 专业阶段:
    - a. 本章导览: ch2/index.md
    - b. QEMU 初始化: ch2/sec1/qemu-init.md
    - c. QEMU 加速器:
      - Tiny Code Generator:
        - TCG Translation: ch2/sec2/qemu-accel-tcg/tcg-translation.md
        - Decodetree: ch2/sec2/qemu-accel-tcg/tcg-add-guest-insn.md
        - TCG IR: ch2/sec2/qemu-accel-tcg/tcg-ir.md
      - Hypervisor: ch2/sec2/qemu-accel-kvm.md
    - d. QEMU Arch 模拟:
        - RISC-V 模拟: ch2/sec3/qemu-tcg-riscv.md
    - e. QEMU 硬件建模:
        - C 语言建模:
          - Machine 建模: ch2/sec4/c-model/machine-model.md
          - 外设建模（串口）: ch2/sec4/c-model/peripheral-model-uart.md
          - 外设建模（edu）: ch2/sec4/c-model/peripheral-model-edu.md
          - 中断建模: ch2/sec4/c-model/intr-model.md
        - Rust 建模:
          - Rust in QEMU: ch2/sec4/rust-model/rust-in-qemu.md
          - QOM 实现: ch2/sec4/rust-model/rust-qom.md
          - QDev 实现: ch2/sec4/rust-model/rust-qdev.md
          - 外设建模: ch2/sec4/rust-model/peripheral-model.md
    - f. QEMU 调试:
      - 远程调试: ch2/sec5/gdbstub.md
      - 日志调试: ch2/sec5/qemu-log.md
      - 追踪事件: ch2/sec5/trace-event.md
    - g. QEMU 测试:
        - Qtest: ch2/sec6/qtest.md
        - TCG 测试: ch2/sec6/test-tcg.md
    - h. QEMU 虚拟化实践: ch2/sec7/qemu-virtual.md
  - 4. 项目阶段:
    - a. 本章导览: ch3/index.md
    - b. QEMU 建模 K230: ch3/sec1/k230-model.md
    - c. QEMU 测评 OS: ch3/sec2/os-test.md
  - 5. 课程附录:
    - a. G233 Datasheet: ch4/g233-board-datasheet.md
